version: "3"
services:
  react-app:
    build:
      context: "./react-app/"
      dockerfile: "Dockerfile"
    depends_on:
      - hormone-service
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/opt/app

  hormone-service:
    build:
      context: "./hormone-service/"
      dockerfile: "Dockerfile"
    depends_on:
      - hormone-service-db
    ports:
      - "7101:7101"
    volumes:
      - ./hormone-service:/opt/app

  hormone-service-db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - "5432:5432"
