version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7300:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  users-service:
    build:
      context: "./user-service/"
      dockerfile: "Dockerfile"
    depends_on:
      - user-service-db
      - auth-service-db
    ports:
      - "7101:7101"
    volumes:
      - ./user-service:/opt/app

  user-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "7201:3306"
